name: Prek

on:
  workflow_call:

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v8

      - name: Run prek
        run: uvx prek run --all-files
